apiVersion: v1
kind: Service

metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}

spec:
  type: LoadBalancer
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: http
      port: 8080